//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToFridge", ReplyAction="http://tempuri.org/IService1/addToFridgeResponse")]
        string addToFridge(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addToFridge", ReplyAction="http://tempuri.org/IService1/addToFridgeResponse")]
        System.Threading.Tasks.Task<string> addToFridgeAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromFridge", ReplyAction="http://tempuri.org/IService1/removeFromFridgeResponse")]
        string removeFromFridge(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeFromFridge", ReplyAction="http://tempuri.org/IService1/removeFromFridgeResponse")]
        System.Threading.Tasks.Task<string> removeFromFridgeAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRecommendations", ReplyAction="http://tempuri.org/IService1/getRecommendationsResponse")]
        string getRecommendations(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getRecommendations", ReplyAction="http://tempuri.org/IService1/getRecommendationsResponse")]
        System.Threading.Tasks.Task<string> getRecommendationsAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/evaluateRecipe", ReplyAction="http://tempuri.org/IService1/evaluateRecipeResponse")]
        string evaluateRecipe(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/evaluateRecipe", ReplyAction="http://tempuri.org/IService1/evaluateRecipeResponse")]
        System.Threading.Tasks.Task<string> evaluateRecipeAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/inquirePreferences", ReplyAction="http://tempuri.org/IService1/inquirePreferencesResponse")]
        string inquirePreferences(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/inquirePreferences", ReplyAction="http://tempuri.org/IService1/inquirePreferencesResponse")]
        System.Threading.Tasks.Task<string> inquirePreferencesAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removePreferences", ReplyAction="http://tempuri.org/IService1/removePreferencesResponse")]
        string removePreferences(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removePreferences", ReplyAction="http://tempuri.org/IService1/removePreferencesResponse")]
        System.Threading.Tasks.Task<string> removePreferencesAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/inquireAllergies", ReplyAction="http://tempuri.org/IService1/inquireAllergiesResponse")]
        string inquireAllergies(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/inquireAllergies", ReplyAction="http://tempuri.org/IService1/inquireAllergiesResponse")]
        System.Threading.Tasks.Task<string> inquireAllergiesAsync(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeAllergies", ReplyAction="http://tempuri.org/IService1/removeAllergiesResponse")]
        string removeAllergies(string[] args);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/removeAllergies", ReplyAction="http://tempuri.org/IService1/removeAllergiesResponse")]
        System.Threading.Tasks.Task<string> removeAllergiesAsync(string[] args);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string addToFridge(string[] args) {
            return base.Channel.addToFridge(args);
        }
        
        public System.Threading.Tasks.Task<string> addToFridgeAsync(string[] args) {
            return base.Channel.addToFridgeAsync(args);
        }
        
        public string removeFromFridge(string[] args) {
            return base.Channel.removeFromFridge(args);
        }
        
        public System.Threading.Tasks.Task<string> removeFromFridgeAsync(string[] args) {
            return base.Channel.removeFromFridgeAsync(args);
        }
        
        public string getRecommendations(string[] args) {
            return base.Channel.getRecommendations(args);
        }
        
        public System.Threading.Tasks.Task<string> getRecommendationsAsync(string[] args) {
            return base.Channel.getRecommendationsAsync(args);
        }
        
        public string evaluateRecipe(string[] args) {
            return base.Channel.evaluateRecipe(args);
        }
        
        public System.Threading.Tasks.Task<string> evaluateRecipeAsync(string[] args) {
            return base.Channel.evaluateRecipeAsync(args);
        }
        
        public string inquirePreferences(string[] args) {
            return base.Channel.inquirePreferences(args);
        }
        
        public System.Threading.Tasks.Task<string> inquirePreferencesAsync(string[] args) {
            return base.Channel.inquirePreferencesAsync(args);
        }
        
        public string removePreferences(string[] args) {
            return base.Channel.removePreferences(args);
        }
        
        public System.Threading.Tasks.Task<string> removePreferencesAsync(string[] args) {
            return base.Channel.removePreferencesAsync(args);
        }
        
        public string inquireAllergies(string[] args) {
            return base.Channel.inquireAllergies(args);
        }
        
        public System.Threading.Tasks.Task<string> inquireAllergiesAsync(string[] args) {
            return base.Channel.inquireAllergiesAsync(args);
        }
        
        public string removeAllergies(string[] args) {
            return base.Channel.removeAllergies(args);
        }
        
        public System.Threading.Tasks.Task<string> removeAllergiesAsync(string[] args) {
            return base.Channel.removeAllergiesAsync(args);
        }
    }
}
